### ISSUE TITLE
Text node speed parameter inverted

### ISSUE THREAD

**Issue by akirasrebirth** [grimepoch/structure_bugs#1]
In the text nodes, the first parameter (speed) is inverted. The speed decreases if the CV input increases.

**Comment by grimepoch** [comment]
Made updates to the following to swap the direction.  This will be fixed in v2.3

bwFadeInOut
bwHDropIn
bwLargeIn
bwRandCharIn
bwRandIn
bwRotateIn
bwSlide
bwSpinScale
bwTypeCursIn
bwTypeIn
bwVFlipIn
fadeIOword
outlineISH
redbwRandCharIn
rgbGraffiti
