### ISSUE TITLE
CC numbers on parameters page not visible

### ISSUE THREAD

**Issue by akirasrebirth** [grimepoch/structure_bugs#3]
![20200113_202015](https://user-images.githubusercontent.com/6773694/72300026-ef6fd500-3662-11ea-93a1-58c8aa5b2d3c.jpg)

**Comment by grimepoch** [comment]
Updated, shrank the font a bit for just the CC lines.  Remember to that S#XX stands for the slot number you have assigned a CC to which you can check on the MOD MATRIX page.

This will be released in v2.3
