### ISSUE TITLE
Bug: Crashes on Reset AutoRot Nodeset

### ISSUE THREAD

**Issue by LarsDanielTerkelsen** [grimepoch/structure_bugs#9]
Node set: GEN1-OUT. In Parameter, I scroll to the bottom setting: Reset AutoRot NodeSet. If I click PREV or NEXT, it re-boots every time.

**Comment by grimepoch** [comment]
Replicated here, will be in next release.

**Comment by grimepoch** [comment]
Fixed.  For now you can just change it with the "SETTING" control, will be in v3.4

**Comment by LarsDanielTerkelsen** [comment]
Not that it matters, but it actually also crashes when you try to change it via SETTING.

**Comment by grimepoch** [comment]
That will get fixed too, same problem in that case.  Problem with uninitialized pointer that should actually point to NULL in the case of the performance settings, and, be ignored if set to to NULL.
